services:
  - type: web
    name: sri-jarvis
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install && npm run build && npm run build:server
    startCommand: node server.mjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
