import { test, describe, after } from 'node:test';
import assert from 'node:assert/strict';
import { ModelRouter } from '../src/providers/ModelRouter';
import { ProviderRegistry } from '../src/providers/ProviderRegistry';
import { prisma } from '../src/lib/db';

describe('Phase 7: J.A.R.V.I.S. Model Router & Multi-Provider Resilience', () => {
  after(async () => {
    try {
      await (prisma as any).$disconnect();
    } catch {}
    // Reset circuit breakers
    ProviderRegistry.resetProviderCircuit('gemini');
    ProviderRegistry.resetProviderCircuit('groq');
    ProviderRegistry.resetProviderCircuit('anthropic');
  });

  test('ModelRouter routes coding tasks prioritizing free and low-cost models', () => {
    const candidates = ModelRouter.route({ taskType: 'coding' });
    assert.ok(candidates.length > 0, 'Must have coding candidates');

    // All returned candidates must support coding
    for (const c of candidates) {
      assert.ok(c.capabilities.includes('coding'), `Model ${c.id} must have coding capability`);
    }

    // Free/Low-cost models must come before paid models
    const freeOrLowCostIndex = candidates.findIndex((c) => c.tier === 'FREE' || c.tier === 'LOW_COST');
    const paidIndex = candidates.findIndex((c) => c.tier === 'PAID');
    assert.ok(freeOrLowCostIndex !== -1, 'Must have free/low-cost candidate');
    if (paidIndex !== -1) {
      assert.ok(freeOrLowCostIndex < paidIndex, 'Free/Low-cost candidates must rank before Paid candidates');
    }
  });

  test('ModelRouter filters candidates by context window and reasoning capability', () => {
    // 1. Architecture tasks require reasoning
    const archCandidates = ModelRouter.route({ taskType: 'architecture' });
    for (const c of archCandidates) {
      assert.ok(c.capabilities.includes('reasoning'), `Model ${c.id} must support reasoning`);
    }

    // 2. High-context requirement (>= 500,000 tokens)
    const highContextCandidates = ModelRouter.route({
      taskType: 'research',
      minContextWindow: 500_000,
    });
    for (const c of highContextCandidates) {
      assert.ok(c.contextWindow >= 500_000, `Model ${c.id} must have >= 500k context window`);
    }
  });

  test('ModelRouter automatically fails over when primary provider fails', async () => {
    let callAttempts: string[] = [];

    const response = await ModelRouter.executeWithFailover(
      { taskType: 'coding' },
      [{ role: 'user', content: 'Refactor auth middleware' }],
      async (model) => {
        callAttempts.push(model.id);
        if (callAttempts.length === 1) {
          // Primary candidate fails with simulated rate limit error
          throw new Error('HTTP 429: Quota exceeded for primary provider');
        }
        // Secondary candidate succeeds
        return `// Successfully generated by ${model.name}\nexport function verifyAuth() {}`;
      }
    );

    assert.equal(callAttempts.length, 2, 'Must have attempted primary, then failed over to secondary');
    assert.ok(response.text.includes('verifyAuth'), 'Must return valid output from failover candidate');
    assert.ok(response.usage.promptTokens > 0, 'Prompt tokens must be computed');
    assert.ok(response.usage.completionTokens > 0, 'Completion tokens must be computed');
    assert.ok(response.latencyMs >= 0);
  });

  test('Circuit breaker trips and excludes repeatedly failing providers', () => {
    // Record 3 consecutive failures on 'groq'
    ProviderRegistry.recordProviderFailure('groq');
    ProviderRegistry.recordProviderFailure('groq');
    ProviderRegistry.recordProviderFailure('groq');

    const groqModel = ProviderRegistry.getModel('groq-llama3-70b');
    assert.equal(groqModel?.healthy, false, 'Model must be marked unhealthy by circuit breaker');

    // Verify router excludes unhealthy models
    const activeCandidates = ModelRouter.route({ taskType: 'coding' });
    const hasGroq = activeCandidates.some((c) => c.provider === 'groq');
    assert.equal(hasGroq, false, 'Unhealthy provider models must be excluded from routing');

    // Reset circuit breaker
    ProviderRegistry.resetProviderCircuit('groq');
    assert.equal(ProviderRegistry.getModel('groq-llama3-70b')?.healthy, true);
  });

});
